# Generated by Django 3.1.3 on 2020-11-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
