# Generated by Django 3.1.3 on 2020-11-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'permissions': (('admin_permission', 'admin permission'),), 'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
    ]
