# Generated by Django 3.1.3 on 2020-11-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201126_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='isSeller',
            new_name='idSeller',
        ),
    ]
