# Generated by Django 3.1.3 on 2020-11-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201126_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='quantitySale',
            field=models.IntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Shortages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortageData', models.DateField(verbose_name='Дата')),
                ('quantityShortage', models.IntegerField(verbose_name='Количество')),
                ('idSeller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
            options={
                'verbose_name': 'Недостача',
                'verbose_name_plural': 'Недостачи',
                'permissions': (('admin_permission', 'admin permission'),),
            },
        ),
    ]
