# Generated by Django 3.1.3 on 2020-11-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201126_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=20, verbose_name='Отчество')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('mail', models.CharField(max_length=20, verbose_name='Почтовый адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'permissions': (('admin_permission', 'admin permission'),),
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='brand',
            field=models.CharField(max_length=20, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
