# Generated by Django 3.1.3 on 2020-11-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201126_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=20, verbose_name='Отчество')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('mail', models.CharField(max_length=20, verbose_name='Почтовый адрес')),
                ('salary', models.IntegerField(verbose_name='Запрплата')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'permissions': (('admin_permission', 'admin permission'),),
            },
        ),
    ]
