# Generated by Django 3.1.3 on 2020-11-27 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.clients'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortages',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
            preserve_default=False,
        ),
    ]
